# Uncomment the next line to define a global platform for your project
# platform :ios, ’8.0’

target 'LearnJapanese' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    	pod 'MagicalRecord'
	pod 'Alamofire'
	pod 'FGTranslator'
	pod 'AFNetworking'
	pod 'SVProgressHUD'

  # Pods for LearnJapanese

  target 'LearnJapaneseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LearnJapaneseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
