# Uncomment the next line to define a global platform for your project
# platform :ios, ’10.0’

target 'LearnJapanese' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    	pod 'MagicalRecord'
	pod 'Alamofire'

  # Pods for LearnJapanese

  target 'LearnJapaneseTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Nocilla', '~> 0.9'
  end

  target 'LearnJapaneseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
